### ISSUE TITLE
Any option to skip certain validation?

### ISSUE THREAD

**Issue by nafalabi** [Hypersequent/zen#10]
Hi, love this package, it helps me a lot in my development!

does it have any option to skip certain validations from the go validator?

for example, I have this type definition in go
```
type SomeType struct {
   Name        string `json:"name"`
   Image        string `json:"image" validate:"uri"`
}
```
currently, it doesn't allow me to convert into TS and gives this error message  `panic: unknown validation: uri`
I assume it's because Zod doesn't support uri validation?

I want to make it ignore the validation part and leave it without validation for this specific attribute, as below
```
export const SomeStructSchema = z.object({
  name: z.string(),
  image: z.string(),
});
```

any idea how I can do that?

**Comment by nafalabi** [comment]
Hi, I have solved this problem by creating an ignore list to skip the conversion on my personal repo
https://github.com/nafalabi/zen/commit/deb5a78c2e3ade70bdd3211e01f917dd033eb433
I'm not sure if this is worth enough to be a PR, but if it is I will gladly create it
Thanks again!

**Comment by satvik007** [comment]
@nafalabi Hey sorry we didn't get to you earlier, could you make a PR. We will happy to merge it.

Possible options are 
- Provide a list of validations as input which we can ignore (probably what you did)
- Print warnings instead of panics

**Comment by nafalabi** [comment]
Hi @satvik007 yes sure thing!
