### ISSUE TITLE
panic: unknown validation: omitempty

### ISSUE THREAD

**Issue by ramilamparo** [Hypersequent/zen#5]
Having `valdate:"omitempty"` crashes zen.

```go

type Schema struct {
  Title *string `json:"title" validate:"omitempty,max=255"`
}

```

Expected: It should ignore `omitempty` validations

Actual: Zen crashes

**Comment by gornostay25** [comment]
https://github.com/Hypersequent/zen/pull/6#pullrequestreview-1684783398
